"use client";
import Link from "next/link";
import { Download, Plus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { addToast } from "@heroui/toast";
import { CustomerDetailDrawer } from "./CustomerDetailDrawer";
import { customers as mockCustomers, type Customer } from "./customer-data";
import { CustomerStatsCards } from "./CustomerStatsCards";
import { CustomersTable } from "./CustomersTable";
import { CustomersToolbar, type Filters } from "./CustomersToolbar";
import { Pagination } from "./Pagination";

type ApiCustomer = { customerId: number; username: string; email: string; phoneNumber?: string; profileImage?: string; accountStatus?: string; location?: { city?: string; country?: string }; orderCount?: number; totalSpent?: number; lastOrder?: { orderId: number; orderDate: string; total: number; status: string } | null };
type ApiPage = { content: ApiCustomer[]; totalElements: number; totalPages: number; number: number };
const initialFilters: Filters = { status: "all", location: "all", type: "all", sort: "Newest" };
const toStatus = (value?: string): Customer["status"] => value?.toUpperCase() === "BLOCKED" ? "Blocked" : value?.toUpperCase() === "INACTIVE" ? "Inactive" : "Active";
const toCustomer = (item: ApiCustomer): Customer => ({ id: item.customerId, name: item.username, email: item.email, phone: item.phoneNumber ?? "—", avatar: item.profileImage || (undefined as unknown as string), location: item.location?.city ?? "—", country: item.location?.country ?? "—", orderCount: item.orderCount ?? 0, totalSpent: item.totalSpent ?? 0, lastOrderDate: item.lastOrder?.orderDate ?? new Date().toISOString(), status: toStatus(item.accountStatus), joinedDate: new Date().toISOString(), orders: item.lastOrder ? [{ id: `ORD-${item.lastOrder.orderId}`, date: item.lastOrder.orderDate, amount: item.lastOrder.total, status: item.lastOrder.status === "CANCELLED" ? "Cancelled" : item.lastOrder.status === "PROCESSING" ? "Processing" : "Delivered" }] : [], addresses: [], reviews: [] });

export function CustomersList() {
  const [customerData, setCustomerData] = useState<Customer[]>([]); const [total, setTotal] = useState(0); const [search, setSearch] = useState(""); const [filters, setFilters] = useState<Filters>(initialFilters); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(20); const [selected, setSelected] = useState<Set<number>>(new Set()); const [opened, setOpened] = useState<Customer | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); try { const response = await fetch(`/api/admin/customers?page=${page}&size=${pageSize}&search=${encodeURIComponent(search)}`, { signal: controller.signal }); const raw = await response.text(); let result: { payload?: ApiPage; message?: string } | null = null; try { result = raw ? JSON.parse(raw) as { payload?: ApiPage; message?: string } : null; } catch { throw new Error(`Customer API returned invalid JSON (HTTP ${response.status}).`); } if (!response.ok || !result?.payload) throw new Error(result?.message ?? `Customer API returned HTTP ${response.status}.`); setCustomerData(result.payload.content.map(toCustomer)); setTotal(result.payload.totalElements); setError(null); } catch (cause) { if (!controller.signal.aborted) { setError(cause instanceof Error ? cause.message : "Unable to load customers."); setCustomerData(mockCustomers.slice(page * pageSize, (page + 1) * pageSize)); setTotal(mockCustomers.length); } } finally { if (!controller.signal.aborted) setLoading(false); } }, 250); return () => { controller.abort(); clearTimeout(timer); }; }, [page, pageSize, search]);
  useEffect(() => { const deleteSelected = async () => { const ids = [...selected]; if (!ids.length) return; const results = await Promise.all(ids.map(async (id) => { const response = await fetch(`/api/admin/customers/${id}`, { method: "DELETE" }); const body = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(body?.message ?? `Unable to delete customer ${id}.`); return id; })); setCustomerData((current) => current.filter((customer) => !results.includes(customer.id))); setSelected(new Set()); setTotal((current) => Math.max(0, current - results.length)); addToast({ title: `${results.length} customer${results.length === 1 ? "" : "s"} deleted`, color: "success" }); }; const handler = () => { void deleteSelected().catch((cause) => addToast({ title: "Delete failed", description: cause instanceof Error ? cause.message : "Unable to delete selected customers.", color: "danger" })); }; window.addEventListener("admin-customers:delete-selected", handler); return () => window.removeEventListener("admin-customers:delete-selected", handler); }, [selected]);
  const locations = useMemo(() => [...new Set(customerData.map((customer) => customer.country).filter((country) => country !== "—"))], [customerData]); const filtered = useMemo(() => customerData.filter((customer) => (filters.status === "all" || customer.status === filters.status) && (filters.location === "all" || customer.country === filters.location) && (filters.type === "all" || (filters.type === "New" ? customer.orderCount <= 1 : customer.orderCount > 1))).sort((a,b) => filters.sort === "Highest Spend" ? b.totalSpent-a.totalSpent : filters.sort === "Most Orders" ? b.orderCount-a.orderCount : filters.sort === "Name A-Z" ? a.name.localeCompare(b.name) : 0), [customerData, filters]);
  const reset = () => { setSearch(""); setFilters(initialFilters); setPage(0); }; const toggle = (id: number) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; }); const toggleAll = () => setSelected((current) => { const next = new Set(current); const all = filtered.every((customer) => next.has(customer.id)); filtered.forEach((customer) => all ? next.delete(customer.id) : next.add(customer.id)); return next; }); const updateStatus = (id: number, status: Customer["status"]) => { setCustomerData((current) => current.map((customer) => customer.id === id ? { ...customer, status } : customer)); setOpened((current) => current?.id === id ? { ...current, status } : current); };
  return <div className="space-y-4 p-6"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-800">Customers</h1><p className="mt-1 text-sm text-slate-500">{total} customers</p></div><div className="flex gap-3"><button onClick={() => addToast({ title: "Customer export started", color: "success" })} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm hover:bg-slate-50"><Download className="h-4 w-4" />Export</button><Link href="/admin/customers/create" className="inline-flex h-10 items-center gap-2 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"><Plus className="h-4 w-4" />Add Customer</Link></div></div><CustomerStatsCards /><CustomersToolbar search={search} setSearch={(value) => { setSearch(value); setPage(0); }} filters={filters} setFilters={setFilters} selectedCount={selected.size} locations={locations} onClear={reset} />{error && <p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">{error} Showing local sample data instead.</p>}{loading ? <div className="rounded-xl bg-white p-12 text-center text-sm text-slate-500 shadow-sm">Loading customers…</div> : <CustomersTable customers={filtered} selected={selected} onToggle={toggle} onToggleAll={toggleAll} onOpen={setOpened} onClear={reset} />}<Pagination page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={(value) => { setPageSize(value); setPage(0); }} /><CustomerDetailDrawer customer={opened} onClose={() => setOpened(null)} onStatusChange={updateStatus} /></div>;
}
