export type CustomerStatus = "Active" | "Inactive" | "Blocked";
export type Customer = { id: number; name: string; email: string; phone: string; avatar: string; location: string; country: string; orderCount: number; totalSpent: number; lastOrderDate: string; status: CustomerStatus; joinedDate: string; orders: { id: string; date: string; amount: number; status: "Delivered" | "Processing" | "Cancelled" }[]; addresses: { label: string; value: string }[]; reviews: { product: string; rating: number; comment: string; date: string }[] };

const people = [["Olivia","Martin"],["Noah","Wilson"],["Emma","Johnson"],["Liam","Brown"],["Ava","Davis"],["Ethan","Miller"],["Sophia","Garcia"],["Mason","Moore"],["Isabella","Taylor"],["Lucas","Anderson"],["Mia","Thomas"],["James","Jackson"]] as const;
const places = [["New York","United States"],["London","United Kingdom"],["Toronto","Canada"],["Sydney","Australia"],["Berlin","Germany"],["Paris","France"],["Singapore","Singapore"],["Tokyo","Japan"]] as const;

export const customers: Customer[] = Array.from({ length: 58 }, (_, index) => {
  const [first, last] = people[index % people.length]; const [location, country] = places[index % places.length]; const count = (index * 3 + 1) % 9; const name = `${first} ${last}`;
  return { id: index + 1001, name, email: `${first.toLowerCase()}.${last.toLowerCase()}${index + 1}@example.com`, phone: `+1 (555) ${String(120 + index).padStart(3, "0")}-${String(1000 + index * 17).slice(-4)}`, avatar: `https://i.pravatar.cc/96?img=${(index % 70) + 1}`, location, country, orderCount: count, totalSpent: Number((count * 64.5 + index * 8.35 + 22).toFixed(2)), lastOrderDate: new Date(2026, 8 - (index % 7), 2 + (index % 25)).toISOString(), status: index % 17 === 0 ? "Blocked" : index % 9 === 0 ? "Inactive" : "Active", joinedDate: new Date(2024 + index % 2, index % 12, 3 + index % 22).toISOString(), orders: Array.from({ length: Math.max(1, count) }, (_, orderIndex) => ({ id: `ORD-${10001 + index * 11 + orderIndex}`, date: new Date(2026, 8 - orderIndex, 1 + orderIndex * 3).toISOString(), amount: Number((35 + index * 5.5 + orderIndex * 22).toFixed(2)), status: orderIndex === 1 ? "Processing" : "Delivered" })), addresses: [{ label: "Shipping", value: `${24 + index} Market Street, ${location}, ${country}` }, { label: "Billing", value: `${180 + index} Oak Avenue, ${location}, ${country}` }], reviews: [{ product: ["Wireless Headphones", "Minimal Lamp", "Travel Bag"][index % 3], rating: 3 + index % 3, comment: "Lovely quality and fast delivery. I would happily order again.", date: new Date(2026, 7, 3 + index % 20).toISOString() }] };
});
