import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { AdminShell } from "../../../AdminShell";
import { CustomerForm } from "../../CustomerForm";
import type { Customer } from "../../customer-data";

type BackendCustomer = { customerId: number; username: string; email: string; phoneNumber?: string; profileImage?: string; accountStatus?: string; location?: { city?: string; country?: string }; orderCount?: number; totalSpent?: number; lastOrder?: { orderId: number; orderDate: string; total: number; status: string } | null };
const backendUrl = (process.env.API_URL ?? process.env.NEXT_PUBLIC_API_URL)?.replace(/\/$/, "");
const status = (value?: string): Customer["status"] => value?.toUpperCase() === "BLOCKED" ? "Blocked" : value?.toUpperCase() === "INACTIVE" ? "Inactive" : "Active";
const mapCustomer = (item: BackendCustomer): Customer => ({ id: item.customerId, name: item.username, email: item.email, phone: item.phoneNumber ?? "", avatar: item.profileImage ?? "", location: item.location?.city ?? "", country: item.location?.country ?? "", orderCount: item.orderCount ?? 0, totalSpent: item.totalSpent ?? 0, lastOrderDate: item.lastOrder?.orderDate ?? new Date().toISOString(), status: status(item.accountStatus), joinedDate: new Date().toISOString(), orders: item.lastOrder ? [{ id: `ORD-${item.lastOrder.orderId}`, date: item.lastOrder.orderDate, amount: item.lastOrder.total, status: item.lastOrder.status === "PROCESSING" ? "Processing" : item.lastOrder.status === "CANCELLED" ? "Cancelled" : "Delivered" }] : [], addresses: [], reviews: [] });

export default async function EditCustomerPage({ params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session?.user) redirect("/login"); if (!(session.user as { roles?: string[] }).roles?.includes("ADMIN")) redirect("/"); const { id } = await params; const customerId = Number(id); if (!Number.isInteger(customerId) || customerId < 1 || !backendUrl) notFound(); const token = (session as typeof session & { backendAccessToken?: string }).backendAccessToken; if (!token) redirect("/login"); const response = await fetch(`${backendUrl}/admin/customers?page=0&size=1000`, { headers: { Authorization: `Bearer ${token.replace(/^Bearer\s+/i, "")}` }, cache: "no-store" }); const result = await response.json().catch(() => null) as { payload?: { content?: BackendCustomer[] } } | null; const found = result?.payload?.content?.find((item) => item.customerId === customerId); if (!response.ok || !found) notFound(); return <AdminShell><CustomerForm mode="edit" customer={mapCustomer(found)} /></AdminShell>; }
