/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import type { TopProduct } from "@/types/dashboard";

export function TopProductsList({ products }: { products: TopProduct[] }) {
  const maxSold = Math.max(1, ...products.map((product) => product.unitsSold));
  return <section className="rounded-xl border border-gray-100 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-bold text-slate-800">Top Selling Products</h2><Link href="/admin/products" className="text-sm font-semibold text-indigo-500 hover:text-indigo-700">View all products</Link></div><ol className="divide-y divide-gray-100">{products.map((product, index) => <li className="flex items-center gap-3 py-3 transition-colors hover:bg-slate-50/70" key={product.productId}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-md text-xs font-bold ${index === 0 ? "bg-amber-100 text-amber-700" : index === 1 ? "bg-slate-200 text-slate-600" : index === 2 ? "bg-orange-100 text-orange-700" : "bg-indigo-50 text-indigo-600"}`}>{index + 1}</span>{product.image ? <img src={product.image} alt="" className="h-10 w-10 rounded-lg object-cover" /> : <span className="h-10 w-10 rounded-lg bg-slate-100" />}<span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-700">{product.productName}</span><span className="mt-1 block"><span className="block h-1.5 w-full overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-indigo-500" style={{ width: `${Math.round((product.unitsSold / maxSold) * 100)}%` }} /></span></span></span><span className="shrink-0 rounded-full bg-indigo-50 px-2 py-1 text-xs font-semibold text-indigo-600">{product.unitsSold} Sold</span></li>)}{products.length === 0 && <li className="py-8 text-center text-sm text-slate-400">No sales yet.</li>}</ol></section>;
}
